### ISSUE TITLE
Inductive Miner 

### ISSUE THREAD

**Issue by s-j-v-zelst** [rapidprom/rapidprom-source#1]
The inductive miner uses xeslite internally which does not seem to be loaded properly.

**Comment by abolt** [comment]
Exception: java.lang.NoClassDefFoundError
Message: Could not initialize class org.processmining.xeslite.external.MapDBStore
Stack trace:

  org.processmining.xeslite.external.MapDBStore$Builder.build(MapDBStore.java:279)
  org.processmining.xeslite.external.XFactoryExternalStore$MapDBDiskImpl.<init>(XFactoryExternalStore.java:106)
  org.processmining.xeslite.external.XFactoryExternalStore$MapDBDiskImpl.<init>(XFactoryExternalStore.java:97)
  org.processmining.xeslite.external.XFactoryExternalStore$MapDBDiskSequentialAccessImpl.<init>(XFactoryExternalStore.java:192)
  org.processmining.xeslite.external.XFactoryExternalStore$MapDBDiskSequentialAccessWithoutCacheImpl.<init>(XFactoryExternalStore.java:258)
  org.processmining.plugins.InductiveMiner.mining.logSplitter.LogSplitterXorFiltering.split(LogSplitterXorFiltering.java:47)
  org.processmining.plugins.InductiveMiner.mining.logSplitter.LogSplitterXorFiltering.split(LogSplitterXorFiltering.java:26)
  org.processmining.plugins.InductiveMiner.mining.logSplitter.LogSplitterCombination.split(LogSplitterCombination.java:37)
  org.processmining.plugins.InductiveMiner.mining.Miner.splitLog(Miner.java:232)
  org.processmining.plugins.InductiveMiner.mining.Miner.mineNode(Miner.java:103)
  org.processmining.plugins.InductiveMiner.mining.fallthrough.FallThroughTauLoop.fallThrough(FallThroughTauLoop.java:57)
  org.processmining.plugins.InductiveMiner.mining.Miner.findFallThrough(Miner.java:226)
  org.processmining.plugins.InductiveMiner.mining.Miner.mineNode(Miner.java:157)
  org.processmining.plugins.InductiveMiner.mining.Miner.mineNode(Miner.java:112)
  org.processmining.plugins.InductiveMiner.mining.Miner.mineNode(Miner.java:112)
  org.processmining.plugins.InductiveMiner.mining.Miner.mineNode(Miner.java:112)
  org.processmining.plugins.InductiveMiner.mining.Miner.mineNode(Miner.java:112)
  org.processmining.plugins.InductiveMiner.mining.Miner.mineNode(Miner.java:112)
  org.processmining.plugins.InductiveMiner.mining.Miner.mine(Miner.java:43)
  org.processmining.plugins.InductiveMiner.plugins.IMProcessTree.mineProcessTree(IMProcessTree.java:29)
  org.processmining.plugins.InductiveMiner.plugins.IMProcessTree.mineProcessTree(IMProcessTree.java:25)
  org.processmining.plugins.InductiveMiner.plugins.IMPetriNet.minePetriNet(IMPetriNet.java:39)
  org.processmining.plugins.InductiveMiner.plugins.IMPetriNet.minePetriNet(IMPetriNet.java:29)
  org.rapidprom.operators.discovery.InductiveMinerPNOperator.doWork(InductiveMinerPNOperator.java:39)
  com.rapidminer.operator.Operator.execute(Operator.java:1021)
  com.rapidminer.operator.execution.SimpleUnitExecutor.execute(SimpleUnitExecutor.java:76)
  com.rapidminer.operator.ExecutionUnit.execute(ExecutionUnit.java:798)
  com.rapidminer.operator.OperatorChain.doWork(OperatorChain.java:392)
  com.rapidminer.operator.Operator.execute(Operator.java:1021)
  com.rapidminer.Process.run(Process.java:1179)
  com.rapidminer.Process.run(Process.java:1081)
  com.rapidminer.Process.run(Process.java:1034)
  com.rapidminer.Process.run(Process.java:1029)
  com.rapidminer.Process.run(Process.java:1019)
  com.rapidminer.gui.ProcessThread.run(ProcessThread.java:65)
