### ISSUE TITLE
Woflan Cancelation

### ISSUE THREAD

**Issue by s-j-v-zelst** [rapidprom/rapidprom-source#10]
Although this is external code, it would be nice/good if Woflan would better listen to cancellation by timeout

**Comment by s-j-v-zelst** [comment]
I didn't put this on milestone 4.0.0 as it will take too much time to improve this for the 4.0.0 release.

**Comment by joosbuijs** [comment]
Please find below an example file which makes Woflan go into an infinite loop. (remove .txt extension).
[Woflan indef loop example.pnml.txt](https://github.com/rapidprom/rapidprom-source/files/494942/Woflan.indef.loop.example.pnml.txt)

**Comment by abolt** [comment]
Solved!
