### ISSUE TITLE
Removing importers

### ISSUE THREAD

**Issue by s-j-v-zelst** [rapidprom/rapidprom-source#17]
In my humble opinion, I have never ever seen the point of having several log importers (in ProM, or in RapidProM for that manner).
How about selecting the best performing one and ignore all the others?
I think it is a totally useless functionality.

**Comment by abolt** [comment]
The best performing one is the Naive (everything in memory), but there are several people dealing with huge logs that consume all memory, and in that case the MapDB one works like a charm...

I would keep them for these purposes.

**Comment by s-j-v-zelst** [comment]
ok, fair enough, though let's limit the number and add this to the description of the operator.
