### ISSUE TITLE
ETC Precision Operator Warnings

### ISSUE THREAD

**Issue by s-j-v-zelst** [rapidprom/rapidprom-source#21]
In the ETC Precision Operator, there are some warnings w.r.t. unused code, i.e.,:
		AlignETCPlugin etc = new AlignETCPlugin();
		AlignETCResult res = new AlignETCResult();
		AlignETCSettings sett = new AlignETCSettings(res);

Are these class instantiations vital or redundant?

**Comment by abolt** [comment]
Not there anymore
