### ISSUE TITLE
Woflan WoflanDiagnosis output is out-of-sync with String output after timeout

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/rapidprom-source#26]
See attached event log and workflow for demo.

If Woflan times out, this is shown in the 'string' output port, but the 'WoflanDiagnosis' output port repeats the previous experiment result.

**Comment by abolt** [comment]
I cannot see the attached event log and workflow. could you re-upload them please?

**Comment by joosbuijs** [comment]
sorry, thought I had saved the ticket, but not submitted yet. Please find log and workflow below.


[APM_Assignment_1.xes.gz](https://github.com/rapidprom/rapidprom-source/files/492831/APM_Assignment_1.xes.gz)

Rapidminer workflow: https://www.dropbox.com/s/duagkodk0crbq7k/WoflanOutputBug.zip?dl=0

**Comment by abolt** [comment]
This was because of the bad cancellation. Now it should be solved :)

**Comment by joosbuijs** [comment]
I checked and the bug does not seem to be solved (I'm using the test version you gave me couple days ago)

**Comment by abolt** [comment]
The output stayed from the previous non-null result.

Now I explicitly make it null :)

**Comment by abolt** [comment]
However, operators that use the normal woflan output should now be contained in a "handle exception" box, otherwise you will get nullpointers...

**Comment by joosbuijs** [comment]
Hi Alfredo, why not produce a string that mentions the timeout? NULL does not provide any context/meaning. You do this in the other, more structured output of the WOFLAN operator.

**Comment by abolt** [comment]
because the first output of woflan is the JComponent that I get from ProM...

In general, people should use the second output of woflan. There I can actually give insights about what happened.

**Comment by joosbuijs** [comment]
It would be preferred if both outputs are 'in sync'. Just generate a JComponent with standard text, in case you don't get a new object from ProM.

**Comment by abolt** [comment]
Hi Joos,

The problem is that Woflan expects an WoflanDiagnosisIOObject in theoutput port. and I cannot create one using a JText...
I could work around it, but this would take a lot of time...

My proposal is to just remove this output.
In any case, the full output is also put in the second output (ExampleSet), so we would not loose anything...

Sounds good to you?

**Comment by joosbuijs** [comment]
Well, the full Woflan result (the object) provides more information in case the PN is unsound, so I prefer to keep this in.
Eric will be in tomorrow, maybe ask him how we can create/instantiate a dummy/empty instance of this object.

**Comment by abolt** [comment]
Ok.

However, the Exampleset has two rows: the first one is the short analysis(sound/unsound/timeout) and the second one prints all the analysis provided by the Woflan object, which is the information that you refer to (I think)

**Comment by joosbuijs** [comment]
Ok, so if the 2nd row also contains the detailed info why something is unsound etc. then the Woflan IO Object can indeed be removed as output.

**Comment by abolt** [comment]
Solved!
