### ISSUE TITLE
New operator suggestions: Murata rules

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/rapidprom-source#27]
Having the Murata operator would be useful to reduce the calculation time of Woflan.

**Comment by abolt** [comment]
It is implemented as the "Reduce Silent Transitions" operator.
This reduces the petri net using the murata rules, while preserving behavoir, soundness of sink/source places (it is a parameter).

Or maybe you mean something different?

**Comment by joosbuijs** [comment]
There is also a more disruptive set of reduction rules that only keeps the rough structure. E.g. 2 activities in sequence are reduce to 1 etc. This greatly reduces the statespace that Woflan builds.

**Comment by abolt** [comment]
Ha! I didn't know it existed. 
Can you tell me which specific ProM package and plugin does that?

**Comment by joosbuijs** [comment]
See the Murata package, there is a reduce-all plug-in. For soundness the end result is the (without the detailed explanation info of course), so clearly state this is in the description!

**Comment by abolt** [comment]
Ok, I will look into this later this week

**Comment by abolt** [comment]
Hi Joos, in your description:

"See the Murata package, there is a reduce-all plug-in. For soundness the end result is the (without the detailed explanation info of course), so clearly state this is in the description!"

I missed something after the "the...". Could you please elaborate on this?

**Comment by joosbuijs** [comment]
I think I meant to add: ‘same’ :)
Eric suggested this to reduce Woflan calculation time. The end conclusion is the same, but of course the details provided related to the reduced net, and not the original.

**Comment by abolt** [comment]
ok!

Then, which of the 3 variants posted above would you like to have in RapidProM?

**Comment by joosbuijs** [comment]
Hi Alfredo,

I think I meant to add: ‘same’ ☺
Eric suggested this to reduce Woflan calculation time. The end conclusion is the same, but of course the details provided related to the reduced net, and not the original.

Met vriendelijke groet/Kind regards,

Joos

**Comment by abolt** [comment]
Done, all 3 implemented
