### ISSUE TITLE
Visualization of Performance Manifest pops-up same dialogs 3 times

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/rapidprom-source#30]
When running the 'Analyze Performance (Manifest)' operator and visualizing its output, the 'timestamp attribute selection' and 'strictly reliable move on model' dialogs pop up 3 times in a row. This seems unnecessary.

**Comment by abolt** [comment]
It is annoying, but changing it would involve getting into the code of that plugin :( (arya's code)
It can be done, but the effort needed may not be worth the return...

I will keep this one open, but not react on it unless @joosbuijs state otherwise

**Comment by joosbuijs** [comment]
I cannot asses the amount of work, and it is merely annoying, not wrong or a bug.
I do wonder however why in the ProM plug-in this is only launched once, but in RapidProM 3x, hence couldn’t the cause be in the RapidProM code?
Nonetheless, I agree with giving this lower priority for now.

**Comment by joosbuijs** [comment]
I cannot asses the amount of work, and it is merely annoying, not wrong or a bug.
I do wonder however why in the ProM plug-in this is only launched once, but in RapidProM 3x, hence couldn’t the cause be in the RapidProM code?
Nonetheless, I agree with giving this lower priority for now.

Met vriendelijke groet/Kind regards,

Joos

**Comment by abolt** [comment]
Solved!

**Comment by joosbuijs** [comment]
Not solved in my 4.0.1. test I'm running right now.

**Comment by joosbuijs** [comment]
Also, although the dialog boxes pop-up 3 times, no visualization is shown.
Alignments are calculated correctly.
