### ISSUE TITLE
Importing of xes.gz files has been fully disabled because of metadata issues

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/rapidprom-source#31]
Importing .xes.gz (e.g. compressed files) is disabled, only uncompressed files can be imported.
This is caused by the fact that metadata can only be derived from uncompressed files currently, this is notably limiting the functionality, requiring users to first uncompress the files is not user friendly.

Possibly related to #8 

@sjvzelsttue or @s-j-v-zelst do you know a solution? (we discussed this a while back but I'm not sure if you had a fix).

**Comment by TaXxER** [comment]
.xes.gz files are not shown in the dialog in which you can select files initially, but my experience is that if you set the dropdown menu for file type from .xes to all files, and then select a .xes.gz file, that it generally loads without problems.

**Comment by abolt** [comment]
Indeed, I removed the .xes.gz from the accepted file types on purpose, but you can go around it as @TaXxER says.

The reason to do this is because the metadata was not being extracted from compressed files. Until we fix it, that filter barrier will hold.

**Comment by abolt** [comment]
Solved!
