### ISSUE TITLE
"Create Sink" option for ILP Miner

### ISSUE THREAD

**Issue by abolt** [rapidprom/rapidprom-source#32]
ILP miner could provide the option to create a sink in the resulting petri net for Soundness analysis. (In ProM as well)

**Comment by s-j-v-zelst** [comment]
I remember I looked into this.
I also rember that I needed some little tweak of Eric's code to get this working.
So far I didn't pursue this yet.

**Comment by s-j-v-zelst** [comment]
A recent theoretical development has enabled us to find relax-sound workflow nets with ILP Miner.
It is already integrated in my branch, Will port this for the next release.
