### ISSUE TITLE
Output of Woflan (2nd) seems to be incorrectly defined

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/rapidprom-source#37]
When I have a workflow where I connect the 2nd output port of the 'Woflan' operator to an operator expecting an exampleSet I get a warning that the operator expects an example set.
Although the workflow works, and the actual output does not seem to be a String but an ExampleSet, this warning could be prevented by updating the return type of the 2nd output port of the Woflan operator.

**Comment by abolt** [comment]
fixed
