### ISSUE TITLE
Output type of the 'Calculate ETC 1-align' seems to be incorrectly defined

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/rapidprom-source#38]
When I have a workflow where I connect the output port of the 'Calculate ETC 1-align' operator to an operator expecting an exampleSet I get a warning that the operator expects an example set.
Although the workflow works, and the actual output does seem to be an ExampleSet, this warning could be prevented by updating the return type of the output port of the 'Calculate ETC 1-align' operator.

**Comment by abolt** [comment]
fixed
