### ISSUE TITLE
Unable to discover process model using alpha miner

### ISSUE THREAD

**Issue by jethefer** [rapidprom/rapidprom-source#39]
Discover process model using Alpha Miner (Petri net) with parameter variant AlphaMiner Classic always return an error with below details:
<img width="822" alt="screen shot 2016-11-21 at 8 42 59 pm" src="https://cloud.githubusercontent.com/assets/23641730/20497871/20f9d790-b02b-11e6-9880-afdf2d197103.png">
How to reproduce:
1. Load .xes file using import event log operator
2. Add Alpha Miner (Petri Net) operator to discover process model
3. Change the parameter variant to AlphaMiner Classic
4. Run

**Comment by abolt** [comment]
Thanks for reporting this!

Indeed, I could reproduce it as well.

**Comment by abolt** [comment]
Fixed! Will be released for 4.0.2
