### ISSUE TITLE
Bug: failed process

### ISSUE THREAD

**Issue by hadisotudeh** [rapidprom/rapidprom-source#40]
Dear @abolt,
There is a bug when I run the attached workflow.

![image](https://cloud.githubusercontent.com/assets/2101643/20524130/2d4ba788-b0b9-11e6-883c-9a993cc89c14.png)

Attached workflow:
[AlphaClassic.zip](https://github.com/rapidprom/rapidprom-source/files/606360/AlphaClassic.zip)

**Comment by abolt** [comment]
Hi Hadi,

Thanks for reporting the bug. It has already been reported #39  and it will be fixed for the next release
