### ISSUE TITLE
Alpha miner classic crashes because of update in PNML package

### ISSUE THREAD

**Issue by joosbuijs** [rapidprom/rapidprom-source#42]
As a student reported to Alfredo, but I don't see a related ticket here.

Please include in 4.0.2. release.

**Comment by s-j-v-zelst** [comment]
it seems that alfredo did update the Petrinet package in 4.0.2 so this seems to be fixed after releasing 4.0.2.
@abolt did you also update all the jars of the packages that actively use the Petrinet package?

**Comment by abolt** [comment]
Duplicated (Solved for 4.0.2).
See #39 and #40

**Comment by s-j-v-zelst** [comment]
maybe keep this open as a reminder for checking all the dependencies?
