### ISSUE TITLE
Data Table to Event Log does not terminate

### ISSUE THREAD

**Issue by mderoode** [rapidprom/rapidprom-source#45]
When using the RapidProM and RapidMiner operators to filter and alter an event log (which has been converted to a Data Table), the Data Table to Event Log does not terminate anymore. The operator keeps running and because it does not give any intermediate status updates, it is hard to identify the root cause. 

Please see the attached workflow and consider the Event Logs of the APM Assignment 3. When executing the script-operator on an Event Log, the E:concept:name is changed (to merge some events with similar name descriptions but different event codes). The Data Table to Event Log does not terminate when the script operator is executed. When removing the script operator, the Data Table to Event Log does terminate. When analyzing the effect of the script operator, it seems that the script operator does invalidate the event log (no unexpected changes to the event log, and all mandatory attributes are still present). The operator should, imho, either give an exception/warning that the input is not supported or just terminate.

I used RapidMiner 7.3.001 and RapidProM 4.0.1. 

[DataTableToLog Workflow.zip](https://github.com/rapidprom/rapidprom-source/files/699402/DataTableToLog.Workflow.zip)

Thanks in advance! 

Mike

**Comment by abolt** [comment]
Hi Mike,

In the APM forum, I made a mistake:

In the Process menu (in the menu bar) you should **check** the "Synchronize Meta Data with Real Data" option. Then, it should finish normally.

Rapidminer tries to synchronize metadata with real data for every row, and it has a 50 milisecond timeout to do so. That is what makes it incredibly slow in big datasets.
If you have the "Synchronize Meta Data with Real Data" option checked, RapidMiner does not attempt to re-do it row-by-row, hence, no 50-milisecond timeouts

Let me know how it goes.

Cheers

**Comment by mderoode** [comment]
Confirmed, the workflow does terminate with the "Synchronize Meta Data with Real Data" option checked. 

Thank you, 

Mike
