### ISSUE TITLE
Wrong categorization of Log Manipulation plug-ins

### ISSUE THREAD

**Issue by fmannhardt** [rapidprom/rapidprom-source#51]
![grafik](https://user-images.githubusercontent.com/3202998/29118147-18e0154e-7d01-11e7-8cdd-3ec3d7345510.png)

Some of the log manipulation operators are filed wrongly. I suggest to move my Log Abstraction category one level up and fix the categorization of the remaining operators.

**Comment by fmannhardt** [comment]
Currently it is also emitting the following error message upon start:
`[Fatal Error] :132:11: Element type "ioobject" must be followed by either attribute specifications, ">" or "/>".
Aug 09, 2017 1:52:39 PM com.rapidminer.gui.renderer.RendererService init
WARNING: Cannot initialize io object description: Cannot parse document: org.xml.sax.SAXParseException; lineNumber: 132; columnNumber: 11; Element type "ioobject" must be followed by either attribute specifications, ">" or "/>".
org.xml.sax.SAXParseException; lineNumber: 132; columnNumber: 11; Element type "ioobject" must be followed by either attribute specifications, ">" or "/>".`

**Comment by s-j-v-zelst** [comment]
fine by me!
