### ISSUE TITLE
Metadata issue

### ISSUE THREAD

**Issue by s-j-v-zelst** [rapidprom/rapidprom-source#8]
Metadata (f.i. available classifiers) is sometimes lost, for instance when using particular operators ( @abolt knows one or more examples).

**Comment by abolt** [comment]
now there is an "Add Classifier" Operator that also creates new metadata based on the classifier that is being added.

I have no way to access the classifiers in the event log from this operator in design-time (when the metadata is used) to this is the closest we can get.

At least now if an event log is generated from a table, you can add a classifier and the following miners will see this classifier in their metadata.
